apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith
  labels:
    app: monolith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monolith
  template:
    metadata:
      labels:
        app: monolith
    spec:
      containers:
        - name: monolith
          image: northamerica-northeast1-docker.pkg.dev/gke-strangler-fig-architecture/reporazakou/monolith:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
