apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: northamerica-northeast1-docker.pkg.dev/gke-strangler-fig-architecture/reporazakou/frontend:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
