apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  labels:
    app: products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: northamerica-northeast1-docker.pkg.dev/gke-strangler-fig-architecture/reporazakou/products:2.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
