apiVersion: v1
kind: Service
metadata:
  name: products
  annotations:
    cloud.google.com/backend-config: '{"ports": {"http":"products-backendconfig"}}'
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
      targetPort: 8082
      protocol: TCP
  selector:
    app: products
