apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  labels:
    app: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: northamerica-northeast1-docker.pkg.dev/gke-strangler-fig-architecture/reporazakou/orders:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
